apiVersion: v1
kind: Namespace
metadata:
  name: status
  labels:
    name: status
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: status
data:
  config.yaml: |
    ui:
      title: "confuzer status"
      description: "status page for confuzer (nextcloud and other services)"
      dashboard-heading: "confuzer status"
      dashboard-subheading: "status page for confuzer (nextcloud and other services)"

    alerting:
      matrix:
        homeserver: "{{MATRIX_HOMESERVER}}"
        access-token: "{{MATRIX_ACCESS_TOKEN}}"
        internal-room-id: "{{MATRIX_ROOM_ID}}"

        default-alert:
          send-on-resolved: true
          failure-threshold: 3
          success-threshold: 2


    endpoints:
      - name: nextcloud
        url: "https://drive.confuzer.cloud"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: refuzer
        url: "https://refuzer.confuzer.cloud"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: backup
        url: "http://backup.confuzer.cloud"
        interval: 60s
        conditions:
          - "[STATUS] == 401"
        alerts:
          - type: matrix

      - name: confuzer
        url: "https://confuzer.cloud"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: test (down on day 1 each month)
        url: "https://status-test.confuzer.cloud"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix


      - name: jjv.sh
        url: "https://jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: multibot
        url: "https://multibot.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: games
        url: "https://games.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: waldo
        url: "https://waldo.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: asciiradio
        url: "https://asciiradio.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: snikket
        url: "https://chat.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: jj electronics
        url: "https://electronics.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: files
        url: "https://f.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: m2m2m
        url: "https://m2m2m.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: rtmp
        url: "https://rtmp.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: status.jjv.sh
        url: "https://status.jjv.sh"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix


      - name: dropposite.tv
        url: "https://dropposite.tv"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: droppo.site
        url: "https://droppo.site"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: sussy factory
        url: "https://sus.ftc7393.org"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: ribbon requestor
        url: "https://ribbon.ftc7393.org"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: vandegriff.net
        url: "https://vandegriff.net"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

      - name: joe.vandegriff.net
        url: "https://joe.vandegriff.net"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 480h"
        alerts:
          - type: matrix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: status
spec:
  replicas: 1 #multiple replicas causes extra pings
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:latest
          ports:
            - containerPort: 8080
          env:
            - name: GATUS_CONFIG_PATH
              value: /config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: gatus-config
---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: status
spec:
  selector:
    app: gatus
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
